export const CURRENCIES_SYMBOLS = {
  'UAH': '₴',
  'USD': '$',
  'EUR': '€',
  'GBP': '£',
  'JPY': '¥',
  'CNY': '¥',
  'RUB': '₽',
  'ILS': '₪',
  'INR': '₨',
  'KRW': '₩',
  'NGN': '₦',
  'THB': '฿',
  'VND': '₫',
  'LAK': '₭',
  'KHR': '៛',
  'MNT': '₮',
  'PHP': '₱',
  'IRR': '﷼',
  'CRC': '₡',
  'PYG': '₲',
  'AFN': '؋',
  'GHS': '₵',
  'KZT': '₸',
  'TRY': '₺',
  'PLN': 'Zł',
};